version: 0.2

phases:

  build:
    commands:
      - dotnet restore
      - dotnet build
      - dotnet publish
artifacts:
  files:
    - ./basic-web-app/site/**/*
    - deployment-app-csharp/aws-windows-deployment-manifest.json